name: "docker-build-push-terraform-plan-apply-notify"

on:
  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      WORKING_DIR: terraform-plan-apply-notify
      IMAGE_NAME: tuana9a/terraform-plan-apply-notify
      tag-commithash: true
      tag-monthly: true
      tag-daily: true
      tag-secondly: true
      push: true
    secrets: inherit
