name: "docker-build-push-tfaa"

on:
  workflow_dispatch:
    inputs:
      scan:
        type: string
        required: false
        default: "no"

jobs:
  main:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      DOCKERFILE_NAME: tfaa.Dockerfile
      IMAGE_NAME: tuana9a/tfaa
      tag-commithash: true
      tag-monthly: true
      tag-daily: true
      tag-secondly: true
      push: true
      scan: "${{ inputs.scan == 'yes' }}"
    secrets: inherit
